#!/usr/bin/python3
"""Les raccourcis de Windows qui marchent ici : binixx-raccourcis liste | verifier | registre."""

import sys

sys.path.insert(0, "/usr/lib/binixx/centre")

from binixx_centre.raccourcis import main  # noqa: E402

sys.exit(main())
